# Generated by Django 3.1.2 on 2021-04-10 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PropertyDocs', '0007_auto_20210410_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewInterface',
            fields=[
                ('bankref_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PropertyDocs.bankref')),
            ],
            bases=('PropertyDocs.bankref',),
            managers=[
                ('viewer', django.db.models.manager.Manager()),
            ],
        ),
    ]
