# Generated by Django 3.2.5 on 2021-07-13 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PropertyDocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewInterface',
            fields=[
                ('bankref_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PropertyDocs.bankref')),
            ],
            bases=('PropertyDocs.bankref',),
            managers=[
                ('viewer', django.db.models.manager.Manager()),
            ],
        ),
    ]
