# Generated by Django 3.2.5 on 2021-07-13 02:01

import ImageUpload.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PropertyDocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ImageUpload.models.get_image_filename, verbose_name='Image')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageUpload.photos')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ImageUpload.models.get_image_filename, verbose_name='Image')),
                ('maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageUpload.maps')),
            ],
        ),
    ]
