# Generated by Django 3.1.2 on 2020-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
    ]
