# Generated by Django 3.1.2 on 2020-12-12 20:27

import ImageUpload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0003_auto_20201210_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=ImageUpload.models.get_image_filename, verbose_name='Image'),
        ),
    ]
