# Generated by Django 3.2.5 on 2021-07-13 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_Number', models.CharField(max_length=250)),
                ('Bank_Type', models.CharField(choices=[('BFL', 'Bajaj Urban'), ('ABHFL', 'Aditya Birla'), ('L&T', 'Larsen Turbo'), ('NA', 'NA')], default='NA', max_length=100)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitLandmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East', models.CharField(blank=True, max_length=300)),
                ('West', models.CharField(blank=True, max_length=300)),
                ('North', models.CharField(blank=True, max_length=300)),
                ('South', models.CharField(blank=True, max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Layout_plan_details', models.CharField(blank=True, max_length=300)),
                ('Approving_authority', models.CharField(blank=True, max_length=300)),
                ('Construction_plan_details', models.CharField(blank=True, max_length=300)),
                ('Plan_validity_from', models.CharField(blank=True, max_length=300)),
                ('To_date', models.CharField(blank=True, max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_Matching', models.BooleanField(blank=True)),
                ('Local_Municipal_body', models.CharField(choices=[('BBMP', 'BBMP'), ('CMC', 'CMC'), ('GP', 'GP'), ('BMRDA', 'BMRDA'), ('NA', 'NA')], default='NA', max_length=50)),
                ('Marketability', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Good', 'Good')], max_length=50)),
                ('Boundaries_matching', models.BooleanField(blank=True)),
                ('Property_Identified', models.BooleanField(blank=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='LegalLandmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East', models.CharField(blank=True, max_length=300)),
                ('West', models.CharField(blank=True, max_length=300)),
                ('North', models.CharField(blank=True, max_length=300)),
                ('South', models.CharField(blank=True, max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_holding_type', models.CharField(choices=[('Freehold', 'Freehold'), ('Leasehold', 'Leasehold')], max_length=50)),
                ('Type_of_the_property', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed_Usage', 'Mixed_Usage')], max_length=50)),
                ('Approved_usage', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed_Usage', 'Mixed_Usage')], max_length=200)),
                ('Actual_usage', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed_Usage', 'Mixed_Usage')], max_length=50)),
                ('Current_Zoning_as_per_CDP', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed_Usage', 'Mixed_Usage')], max_length=50)),
                ('Occupancy_details_floorwise', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SFDC_no', models.CharField(blank=True, max_length=200)),
                ('Report_Date', models.DateField(auto_now=True)),
                ('Product_Loan_Type', models.CharField(choices=[('LAP', 'LAP'), ('HL', 'HL'), ('BT', 'BT'), ('NA', 'NA')], default='NA', max_length=50)),
                ('Person_met_at_site', models.CharField(max_length=200)),
                ('Name_of_Applicant', models.CharField(max_length=200)),
                ('Name_of_Property_Owner_as_per_legal_document', models.CharField(max_length=200)),
                ('Documents_Provided', models.CharField(max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('Client_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Contact', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Date_Time', models.DateField(auto_now=True)),
                ('Slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Created_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankref',
            name='client_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.clientinfo'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postal_address_of_the_property', models.CharField(max_length=300)),
                ('Legal_address_of_the_property', models.CharField(max_length=200)),
                ('Landmark_nearby', models.CharField(max_length=200)),
                ('Lat_and_Long', models.CharField(max_length=200)),
                ('Distance_from_City_Centre', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
    ]
