# Generated by Django 3.1.2 on 2020-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyDocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankref',
            name='Reference_Number',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
