# Generated by Django 3.1.2 on 2020-11-25 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyDocs', '0002_auto_20201121_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitLandmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East', models.CharField(blank=True, max_length=300)),
                ('West', models.CharField(blank=True, max_length=300)),
                ('North', models.CharField(blank=True, max_length=300)),
                ('South', models.CharField(blank=True, max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Layout_plan_details', models.CharField(blank=True, max_length=300)),
                ('Approving_authority', models.CharField(blank=True, max_length=300)),
                ('Construction_plan_details', models.CharField(blank=True, max_length=300)),
                ('Plan_validity_from', models.CharField(blank=True, max_length=300)),
                ('To_date', models.CharField(blank=True, max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_Matching', models.BooleanField(blank=True)),
                ('Local_Municipal_body', models.CharField(choices=[('BBMP', 'BBMP'), ('CMC', 'CMC'), ('GP', 'GP'), ('BMRDA', 'BMRDA'), ('NA', 'NA')], default='NA', max_length=50)),
                ('Marketability', models.CharField(choices=[('LOW', 'LOW'), ('Medium', 'Medium'), ('Good', 'Good')], max_length=50)),
                ('Boundaries_matching', models.BooleanField(blank=True)),
                ('Property_Identified', models.BooleanField(blank=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
        migrations.CreateModel(
            name='LegalLandmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East', models.CharField(blank=True, max_length=300)),
                ('West', models.CharField(blank=True, max_length=300)),
                ('North', models.CharField(blank=True, max_length=300)),
                ('South', models.CharField(blank=True, max_length=300)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
        ),
    ]
