# Generated by Django 3.1.2 on 2020-12-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyDocs', '0003_legallandmarks_marketingvalue_plan_sitevisitlandmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insights',
            name='Approved_usage',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed_Usage', 'Mixed_Usage')], max_length=200),
        ),
        migrations.AlterField(
            model_name='insights',
            name='Current_Zoning_as_per_CDP',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed_Usage', 'Mixed_Usage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingvalue',
            name='Marketability',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Good', 'Good')], max_length=50),
        ),
    ]
