# Generated by Django 3.1.2 on 2020-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyDocs', '0004_auto_20201206_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
