# Generated by Django 3.1.2 on 2020-12-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyDocs', '0005_auto_20201206_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
