# Generated by Django 3.2.5 on 2021-07-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PropertyDocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Land_area', models.PositiveIntegerField(blank=True, null=True)),
                ('BUA_SBUA', models.PositiveIntegerField(blank=True, null=True)),
                ('Interiors', models.PositiveIntegerField(blank=True, null=True)),
                ('Car_park', models.PositiveIntegerField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'TotalValue',
            },
        ),
        migrations.CreateModel(
            name='SanctionedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basement_Stilt_area', models.PositiveIntegerField(blank=True, null=True)),
                ('No_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('GF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('FF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('SF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('TF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('Total', models.PositiveIntegerField(blank=True, null=True)),
                ('FAR_FSI', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'SanctionedArea',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Land_area', models.PositiveIntegerField(blank=True, null=True)),
                ('BUA_SBUA', models.PositiveIntegerField(blank=True, null=True)),
                ('Interiors', models.PositiveIntegerField(blank=True, null=True)),
                ('Car_park', models.PositiveIntegerField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'Rate',
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Progress', models.CharField(max_length=200)),
                ('Recommended', models.CharField(max_length=200)),
                ('CurrentAge', models.CharField(max_length=200)),
                ('ResidualAge', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'PropertyStatus',
            },
        ),
        migrations.CreateModel(
            name='PermissibleBUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basement_Stilt_area', models.PositiveIntegerField(blank=True, null=True)),
                ('No_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('GF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('FF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('SF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('TF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('Total', models.PositiveIntegerField(blank=True, null=True)),
                ('FAR_FSI', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'PermissibleBUA',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approach_Road', models.BooleanField()),
                ('Sewer_system', models.BooleanField()),
                ('Water_supply', models.BooleanField()),
                ('Electricity', models.BooleanField()),
                ('Construction_quality', models.BooleanField()),
                ('No_of_lifts', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'LayoutInfrastructure',
            },
        ),
        migrations.CreateModel(
            name='FinalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValuationDoneEarlier', models.BooleanField(verbose_name=' Validation Done Earlier ?')),
                ('IsNegative', models.BooleanField(verbose_name=' Property in bad community ?')),
                ('IsInDemolitionList', models.BooleanField(verbose_name=' Property in Demolition list ?')),
                ('Remarks', models.TextField()),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'FinalPropertyNotes',
            },
        ),
        migrations.CreateModel(
            name='FairMarketValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.PositiveIntegerField(blank=True, null=True)),
                ('Date', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Distressed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('GovtValue', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'FairMarketValue',
            },
        ),
        migrations.CreateModel(
            name='Deviations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_BUA_deviation', models.CharField(max_length=200)),
                ('Total_SBUA_considered', models.CharField(max_length=200)),
                ('FAR_FSI_deviation', models.CharField(max_length=200)),
                ('Risk_of_Demolition', models.BooleanField()),
                ('Total_Bedrooms', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'Deviations',
            },
        ),
        migrations.CreateModel(
            name='AsPerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East_to_west_in_Feet', models.PositiveIntegerField(blank=True, null=True)),
                ('North_to_South_in_Feet', models.PositiveIntegerField(blank=True, null=True)),
                ('Land_area_or_UDS_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('Carpet_area_of_flat_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('SBUA_of_Flat_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'PlotAreaPlan',
            },
        ),
        migrations.CreateModel(
            name='AsPerDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East_to_west_in_Feet', models.PositiveIntegerField(blank=True, null=True)),
                ('North_to_South_in_Feet', models.PositiveIntegerField(blank=True, null=True)),
                ('Land_area_or_UDS_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('Carpet_area_of_flat_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('SBUA_of_Flat_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'PlotAreaDocuments',
            },
        ),
        migrations.CreateModel(
            name='AreaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Land_area', models.PositiveIntegerField(blank=True, null=True)),
                ('BUA_SBUA', models.PositiveIntegerField(blank=True, null=True)),
                ('Interiors', models.PositiveIntegerField(blank=True, null=True)),
                ('Car_park', models.PositiveIntegerField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'AreaDetails',
            },
        ),
        migrations.CreateModel(
            name='Actuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('East_to_west_in_Feet', models.PositiveIntegerField(blank=True, null=True)),
                ('North_to_South_in_Feet', models.PositiveIntegerField(blank=True, null=True)),
                ('Land_area_or_UDS_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('Carpet_area_of_flat_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('SBUA_of_Flat_in_SFT', models.PositiveIntegerField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'PlotAreaActuals',
            },
        ),
        migrations.CreateModel(
            name='ActualBUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basement_Stilt_area', models.PositiveIntegerField(blank=True, null=True)),
                ('No_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('GF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('FF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('SF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('TF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('Total', models.PositiveIntegerField(blank=True, null=True)),
                ('FAR_FSI', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'ActualBUA',
            },
        ),
    ]
