# Generated by Django 3.1.2 on 2020-12-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuals',
            name='Carpet_area_of_flat_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actuals',
            name='East_to_west_in_Feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actuals',
            name='Land_area_or_UDS_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actuals',
            name='North_to_South_in_Feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actuals',
            name='SBUA_of_Flat_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperdocuments',
            name='Carpet_area_of_flat_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperdocuments',
            name='East_to_west_in_Feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperdocuments',
            name='Land_area_or_UDS_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperdocuments',
            name='North_to_South_in_Feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperdocuments',
            name='SBUA_of_Flat_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperplan',
            name='Carpet_area_of_flat_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperplan',
            name='East_to_west_in_Feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperplan',
            name='Land_area_or_UDS_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperplan',
            name='North_to_South_in_Feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asperplan',
            name='SBUA_of_Flat_in_SFT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
