# Generated by Django 3.1.2 on 2020-12-30 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyDocs', '0006_auto_20201219_2224'),
        ('Technical', '0002_auto_20201226_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorsCommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basement_Stilt_area', models.PositiveIntegerField(blank=True, null=True)),
                ('GF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('FF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('SF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('TF_area_units', models.PositiveIntegerField(blank=True, null=True)),
                ('Total', models.PositiveIntegerField(blank=True, null=True)),
                ('FAR_FSI', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deviations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_BUA_deviation', models.CharField(max_length=200)),
                ('Total_SBUA_considered', models.CharField(max_length=200)),
                ('FAR_FSI_deviation', models.CharField(max_length=200)),
                ('Risk_of_Demolition', models.BooleanField()),
                ('Total_Bedrooms', models.CharField(max_length=200)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'Deviations',
            },
        ),
        migrations.CreateModel(
            name='SanctionedArea',
            fields=[
                ('floorscommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Technical.floorscommoninfo')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'SanctionedArea',
            },
            bases=('Technical.floorscommoninfo',),
        ),
        migrations.CreateModel(
            name='PermissibleBUA',
            fields=[
                ('floorscommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Technical.floorscommoninfo')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'PermissibleBUA',
            },
            bases=('Technical.floorscommoninfo',),
        ),
        migrations.CreateModel(
            name='ActualBUA',
            fields=[
                ('floorscommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Technical.floorscommoninfo')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PropertyDocs.bankref')),
            ],
            options={
                'db_table': 'ActualBUA',
            },
            bases=('Technical.floorscommoninfo',),
        ),
    ]
