# Generated by Django 3.1.2 on 2020-12-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0003_actualbua_deviations_floorscommoninfo_permissiblebua_sanctionedarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorscommoninfo',
            name='No_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
